import { and, eq } from 'drizzle-orm'
import { db, schema } from '@growthos/db'
import { generateContentBrief } from '@growthos/logic'
import { publish } from '../../ws.js'
import type { AutomationAdapter, AdapterResult, StoredAction, ActionTargetShape } from '../types.js'

/**
 * The one adapter with a real side effect today (ROADMAP bullet 4: "automated: add converting search
 * terms to SEO content queue"). It needs no external credentials because both ends are internal —
 * the search term comes from data the app already has, and the content brief lands in the
 * `content_briefs` table the Content Pipeline page already reads.
 *
 * Idempotent on (workspace, keyword). The scheduler proposes on a cadence and an operator can
 * approve the same keyword twice across ticks; a duplicate brief would be user-visible clutter, so
 * a repeat is reported as a skip rather than either failing or silently double-writing.
 *
 * The brief is generated by the same `generateContentBrief` engine `ensurePaidToOrganic` uses, so an
 * automated brief is indistinguishable from a manually-generated one. `recommendationId` is left
 * null: this brief was produced by an automation rule, not by a recommendation someone acted on.
 */
export const contentQueueAdapter: AutomationAdapter = {
  name: 'content-queue',

  async execute(action: StoredAction, workspaceId: string): Promise<AdapterResult> {
    const target = action.target as ActionTargetShape
    const keyword = target.keyword?.trim()

    if (!keyword) {
      return { ok: false, detail: {}, error: 'Action target carries no keyword.' }
    }

    const [existing] = await db
      .select({ id: schema.contentBriefs.id })
      .from(schema.contentBriefs)
      .where(
        and(
          eq(schema.contentBriefs.workspaceId, workspaceId),
          eq(schema.contentBriefs.keyword, keyword),
        ),
      )
      .limit(1)

    if (existing) {
      return {
        ok: true,
        detail: { skipped: true, reason: 'A content brief already exists for this keyword.', keyword, briefId: existing.id },
      }
    }

    const [row] = await db
      .insert(schema.contentBriefs)
      .values({
        workspaceId,
        recommendationId: null,
        keyword,
        source: 'automation_rule',
        sourceData: action.payload,
        brief: generateContentBrief(keyword),
      })
      .returning({ id: schema.contentBriefs.id })

    // Same event the manual path raises, so open Content Pipeline pages refresh either way.
    void publish({
      type: 'recommendation:new',
      workspaceId,
      payload: { count: 1, source: 'automation_content_queue' },
    })

    return { ok: true, detail: { created: true, keyword, briefId: row!.id } }
  },
}
