#!/usr/bin/env node
// `pnpm setup:local` — everything needed before GrowthOS can run locally with zero external
// accounts. Safe to re-run any time: every step here checks what's already true before doing
// anything, so running this twice (or via `pnpm local`, which always runs it first) never
// duplicates work or clobbers a config you've since edited by hand.
//
// What this does NOT do: start the web/API dev servers. That's `pnpm local` (scripts/local/start.mjs),
// which runs everything in this file and then starts them. Use this script directly only if you
// want the infra + demo data ready without the dev servers running yet.

import { existsSync } from "node:fs";
import path from "node:path";
import {
  ok,
  fail,
  info,
  warn,
  heading,
  run,
  runCapture,
  commandExists,
  genHex,
  genBase64,
  ensureEnvFile,
  repoRoot,
} from "./lib.mjs";

export const ROOT = repoRoot();
export const P = (...parts) => path.join(ROOT, ...parts);

// Non-default Postgres port so this can run alongside a system Postgres already on 5432 — see
// docker-compose.local.yml.
export const PORTS = { web: 3000, api: 3001, postgres: 5433, redis: 6379, clickhouse: 8123 };
export const LOCAL_DATABASE_URL = `postgresql://growthos:growthos_local_dev@localhost:${PORTS.postgres}/growthos`;

export const DEMO_EMAIL = "demo@growthos.local";
export const DEMO_PASSWORD = "DemoPass123!";

export async function checkPrereqs() {
  heading("Checking prerequisites");

  const [major] = process.versions.node.split(".").map(Number);
  if (major >= 20) ok(`Node ${process.version}`);
  else {
    fail(`Node ${process.version} — GrowthOS needs Node 20 or newer.`);
    console.log("\n  Install a current Node (e.g. via nvm: https://github.com/nvm-sh/nvm), then re-run this.\n");
    process.exit(1);
  }

  if (!(await commandExists("docker"))) {
    fail("Docker is not installed.");
    console.log("\n  Local Demo Mode needs Docker for Postgres, Redis, and ClickHouse — nothing else to install.");
    console.log("  On Ubuntu / Zorin / Debian:");
    console.log("    sudo apt update && sudo apt install -y docker.io");
    console.log("    sudo usermod -aG docker $USER");
    console.log("  Then log out and back in (group membership needs a fresh session), and re-run this.\n");
    process.exit(1);
  }
  ok("Docker is installed");

  const { code } = await runCapture("docker", ["info"]);
  if (code !== 0) {
    fail("Docker is installed but isn't running (or your user can't reach it).");
    console.log("\n  Start Docker, then re-run this. On Linux, that's usually:");
    console.log("    sudo systemctl start docker");
    console.log("  If you just ran `usermod -aG docker`, log out and back in first.\n");
    process.exit(1);
  }
  ok("Docker is running");
}

export function writeEnvFiles() {
  heading("Setting up local environment files");
  info("Local Demo Mode secrets are generated fresh below — never reuse them anywhere but your laptop.");

  const dbWrote = ensureEnvFile(P("packages/db/.env"), [
    "# Auto-generated by `pnpm setup:local` for Local Demo Mode. Safe to delete and regenerate —",
    "# just re-run `pnpm setup:local`. If you're pointing this at a real Neon database instead,",
    "# replace DATABASE_URL and delete the DATABASE_DRIVER line (it defaults to Neon).",
    `DATABASE_URL=${LOCAL_DATABASE_URL}`,
    "DATABASE_DRIVER=node-postgres",
  ]);
  ok(dbWrote ? "packages/db/.env created" : "packages/db/.env already exists — leaving it as is");

  const apiWrote = ensureEnvFile(P("apps/api/.env"), [
    "# Auto-generated by `pnpm setup:local` for Local Demo Mode. Safe to delete and regenerate —",
    "# just re-run `pnpm setup:local`. These are LOCAL DEVELOPMENT secrets: fine for a laptop demo,",
    "# never reuse generated values in a real deployment.",
    "",
    `API_PORT=${PORTS.api}`,
    `WEB_ORIGIN=http://localhost:${PORTS.web}`,
    "",
    "# Local Postgres (docker-compose.local.yml) — see packages/db/src/client.ts for what",
    "# DATABASE_DRIVER does. To use a real Neon database instead, replace DATABASE_URL and delete",
    "# the DATABASE_DRIVER line.",
    `DATABASE_URL=${LOCAL_DATABASE_URL}`,
    "DATABASE_DRIVER=node-postgres",
    "",
    "# Better Auth — generated automatically, no setup needed.",
    `BETTER_AUTH_SECRET=${genHex(32)}`,
    `BETTER_AUTH_URL=http://localhost:${PORTS.api}`,
    "",
    "# Platform-integration token encryption — generated automatically. Only matters once you",
    "# connect a real Google/Meta account, which Local Demo Mode doesn't need.",
    `TOKEN_ENCRYPTION_KEY=${genBase64(32)}`,
    `OAUTH_STATE_SECRET=${genHex(32)}`,
    "",
    "# Google OAuth — leave blank unless you want to connect a real Google Ads/Search Console",
    "# account. Local Demo Mode's data doesn't need this.",
    "GOOGLE_CLIENT_ID=",
    "GOOGLE_CLIENT_SECRET=",
    `GOOGLE_OAUTH_REDIRECT_URI=http://localhost:${PORTS.api}/api/v1/oauth/callback`,
    "",
    "# Local ClickHouse / Redis (docker-compose.local.yml).",
    `CLICKHOUSE_URL=http://localhost:${PORTS.clickhouse}`,
    `REDIS_URL=redis://localhost:${PORTS.redis}`,
    "",
    "# Everything below is genuinely optional — each feature checks for its own key and no-ops",
    "# rather than crashing when it's blank. Local Demo Mode runs completely without any of these.",
    "STRIPE_SECRET_KEY=",
    "STRIPE_WEBHOOK_SECRET=",
    "STRIPE_PRICE_STARTER=",
    "STRIPE_PRICE_GROWTH=",
    "STRIPE_PRICE_SCALE=",
    "RESEND_API_KEY=",
    "RESEND_FROM_EMAIL=",
    "SENTRY_DSN=",
    "SENTRY_RELEASE=",
    "DB_MAX_RETRIES=",
  ]);
  ok(apiWrote ? "apps/api/.env created (secrets generated)" : "apps/api/.env already exists — leaving it as is");

  const webWrote = ensureEnvFile(P("apps/web/.env"), [
    "# Auto-generated by `pnpm setup:local` for Local Demo Mode. Safe to delete and regenerate.",
    `NEXT_PUBLIC_API_URL=http://localhost:${PORTS.api}`,
    "NEXT_PUBLIC_POSTHOG_KEY=",
    "NEXT_PUBLIC_POSTHOG_HOST=https://us.i.posthog.com",
  ]);
  ok(webWrote ? "apps/web/.env created" : "apps/web/.env already exists — leaving it as is");

  // Optional — only used if you separately choose to run the Python worker (see README's Local
  // Demo Mode section). Not started automatically: it's a different toolchain (Python, not Node),
  // and every dashboard in Local Demo Mode is populated by the seed step below, not by the
  // worker's background jobs.
  const workerWrote = ensureEnvFile(P("apps/worker/.env"), [
    "# Auto-generated by `pnpm setup:local` for Local Demo Mode. Only needed if you run the worker",
    "# yourself — see apps/worker/README.md. Not started by `pnpm local`.",
    `DATABASE_URL=${LOCAL_DATABASE_URL}`,
    `REDIS_URL=redis://localhost:${PORTS.redis}`,
    "QUEUE_KEY=jobs:queue",
    "CLICKHOUSE_HOST=localhost",
    `CLICKHOUSE_PORT=${PORTS.clickhouse}`,
  ]);
  ok(workerWrote ? "apps/worker/.env created" : "apps/worker/.env already exists — leaving it as is");
}

export async function startInfra() {
  heading("Starting Postgres, Redis, and ClickHouse");
  info("docker compose -f docker-compose.local.yml up -d --wait");
  try {
    await run("docker", ["compose", "-f", "docker-compose.local.yml", "up", "-d", "--wait", "--wait-timeout", "120"], {
      cwd: ROOT,
    });
  } catch (err) {
    fail("One or more containers didn't become healthy in time.");
    console.log(`\n  ${err.message}`);
    console.log("\n  Check what's wrong with:");
    console.log("    docker compose -f docker-compose.local.yml ps");
    console.log("    docker compose -f docker-compose.local.yml logs\n");
    process.exit(1);
  }
  ok("Postgres, Redis, and ClickHouse are healthy");
}

export async function installDependencies() {
  if (existsSync(P("node_modules")) && existsSync(P("apps/api/node_modules"))) {
    ok("Dependencies already installed");
    return;
  }
  heading("Installing dependencies (first run only — this takes a minute or two)");
  // Puppeteer's Chromium download is the #1 way a fresh install hangs or fails on a flaky/
  // restricted network — apps/api/.puppeteerrc.cjs skips it by default already, but setting this
  // here too means it's skipped even the very first time, before that config file's package has
  // been resolved.
  await run("pnpm", ["install"], { cwd: ROOT, env: { ...process.env, PUPPETEER_SKIP_DOWNLOAD: "true" } });
  ok("Dependencies installed");
}

export async function pushSchema() {
  heading("Setting up the database schema");
  // `pnpm --filter <pkg> <script> -- <args>` does NOT forward args the way it looks like it
  // should: pnpm includes the literal `--` in what it hands to the script, and drizzle-kit's own
  // CLI rejects that as an "Unrecognized option" — so `db:push -- --force` fails outright, every
  // time, filter or no filter. `exec` sidesteps the whole problem: it runs the binary directly
  // with the args exactly as given, no script-string concatenation involved.
  await run("pnpm", ["--filter", "@growthos/db", "exec", "drizzle-kit", "push", "--force"], {
    cwd: ROOT,
    env: { ...process.env, DATABASE_URL: LOCAL_DATABASE_URL },
  });
  ok("Database schema is up to date");
}

export async function seedDemoData() {
  heading("Seeding demo data");
  await run("pnpm", ["--filter", "@growthos/api", "exec", "tsx", "scripts/seed-demo.ts"], {
    cwd: ROOT,
    env: { ...process.env, DATABASE_URL: LOCAL_DATABASE_URL, DATABASE_DRIVER: "node-postgres" },
  });
}

async function main() {
  await checkPrereqs();
  writeEnvFiles();
  await installDependencies();
  await startInfra();
  await pushSchema();
  await seedDemoData();
  heading("Setup complete");
  console.log("Run `pnpm local` to start GrowthOS.\n");
}

// Only run when invoked directly (`pnpm setup:local`) — start.mjs imports these functions instead.
if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((err) => {
    fail(err.message ?? String(err));
    process.exit(1);
  });
}
