import { betterAuth } from 'better-auth';
import { drizzleAdapter } from 'better-auth/adapters/drizzle';
import { organization } from 'better-auth/plugins';
import { db, schema } from '@growthos/db';

/**
 * Better Auth (M1 · P1.2) — the single source of truth for identity + tenancy (D1).
 *
 * - Drizzle/Neon adapter (D2), email/password to start.
 * - The organization plugin models tenancy. Its tables are mapped to the blueprint's names via
 *   `modelName`: organization → `workspaces`, member → `workspace_members`,
 *   invitation → `workspace_invitations`. Domain columns live as `additionalFields` on the org.
 *
 * The Drizzle tables these map to are generated by the Better Auth CLI into
 * `packages/db/src/schema/auth.ts` and re-exported from `@growthos/db`.
 */
export const auth = betterAuth({
  database: drizzleAdapter(db, { provider: 'pg', schema }),
  secret: process.env.BETTER_AUTH_SECRET,
  baseURL: process.env.BETTER_AUTH_URL ?? 'http://localhost:3001',
  trustedOrigins: [process.env.WEB_ORIGIN ?? 'http://localhost:3000'],
  emailAndPassword: {
    enabled: true,
  },
  user: {
    additionalFields: {
      // Platform-wide admin access (Super Admin panel), separate from per-workspace `role` on
      // workspace_members. `input: false` — deliberately not settable via any signup/profile
      // form; only ever set directly in the database by someone who already has DB access.
      platformRole: { type: 'string', required: false, input: false },
      // Unlike platformRole this IS settable by its owner — it is their own contact number, typed
      // on the admin profile step and saved through Better Auth's own updateUser.
      phone: { type: 'string', required: false, input: true },
    },
  },
  plugins: [
    organization({
      schema: {
        organization: {
          modelName: 'workspaces',
          additionalFields: {
            plan: { type: 'string', required: false, defaultValue: 'starter', input: false },
            websiteUrl: { type: 'string', required: false, input: true },
            businessCategory: { type: 'string', required: false, input: true },
            monthlyAdBudget: { type: 'number', required: false, input: true },
            onboardingStep: {
              type: 'string',
              required: false,
              defaultValue: 'business_intake',
              input: false,
            },
            onboardingComplete: {
              type: 'boolean',
              required: false,
              defaultValue: false,
              input: false,
            },
          },
        },
        member: { modelName: 'workspace_members' },
        invitation: { modelName: 'workspace_invitations' },
      },
    }),
  ],
});

export type Auth = typeof auth;
