import {
  boolean,
  index,
  jsonb,
  pgTable,
  text,
  timestamp,
  unique,
  uuid,
} from 'drizzle-orm/pg-core';
import { workspaces } from './auth.js';

/**
 * Domain tenancy schema (M1 · P1.2).
 *
 * The workspace tables themselves (`workspaces`, `workspace_members`, `workspace_invitations`) plus
 * identity (`user`/`session`/`account`/`verification`) are owned + generated by Better Auth — see
 * `./auth.ts`. This file holds the domain tables that hang off a workspace.
 *
 * `workspaceId` intentionally has no DB-level FK to `workspaces`: Drizzle cross-file `.references()`
 * would require a `./auth.js` import, which drizzle-kit's schema loader cannot resolve (it reads the
 * `.ts` source and can't follow the NodeNext `.js` extension tsc requires). Workspace isolation is
 * enforced at the application layer (Fastify), not via Postgres constraints — see CLAUDE.md. A
 * DB-level FK can be reintroduced later once schema files are consolidated.
 */

// Connected ad / analytics / commerce platforms per workspace.
// platform: google_ads | google_search_console | google_analytics | meta | shopify
//         | woocommerce | hubspot | klaviyo
export const platformConnections = pgTable(
  'platform_connections',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: text('workspace_id')
      .references(() => workspaces.id, { onDelete: 'cascade' })
      .notNull(),
    platform: text('platform').notNull(),
    accountId: text('account_id').notNull(),
    accountName: text('account_name'),
    accessToken: text('access_token').notNull(), // AES-256 encrypted at the app layer
    refreshToken: text('refresh_token'), // AES-256 encrypted at the app layer
    tokenExpiresAt: timestamp('token_expires_at', { withTimezone: true }),
    scopes: text('scopes').array(),
    metadata: jsonb('metadata'), // platform-specific (e.g. GA4 property_id, Shopify store_url)
    isActive: boolean('is_active').default(true),
    lastSyncedAt: timestamp('last_synced_at', { withTimezone: true }),
    syncError: text('sync_error'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
  },
  (t) => [
    unique().on(t.workspaceId, t.platform, t.accountId),
    index('idx_connections_workspace').on(t.workspaceId, t.platform),
  ],
);
